config/routes.rb
Rails.application.routes.draw do
  
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  get 'users/index'

  devise_for :users
  get 'invoice_confirm/edit'
  get 'invoice_confirm/verify'
  put 'invoice_confirm/confirm'
  
  # post 'invoice_confirm/transaction_response'

  match 'invoice_confirm/response' => 'invoice_confirm#transaction_response', via: [:post]
  # post 'invoice_confirm/failure'
  
  resources :users, only:[:index]
  resources :invoices do
    member do
      get :copy
      get :reset
    end
    collection do
      get :failure
    end
  end
  # get 'dashboard/index'

  root 'invoices#index'
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  include AASM
  attr_accessor :is_confirm_invoice, :contact_same_as_above, :is_terms_and_conditions_accepted, :terms_condition
  
  validates :consumer_id, presence: true
  validates :reference_number, presence: true
  validates :amount, presence: true
  validates :currency, presence: true
  validates :security_token, presence: true
  validates :auth_token, presence: true
  validates :transaction_uuid, presence: true
  validates :transaction_type, presence: true

  with_options if: :is_confirm_invoice do |br|
    br.validates :bill_to_forename, presence: true
    br.validates :bill_to_surname, presence: true
    br.validates :bill_to_email, presence: true
    br.validates :bill_to_address_line1, presence: true
    br.validates :bill_to_address_city, presence: true
    br.validates :bill_to_address_postal_code, presence: true
    br.validates :bill_to_address_state, presence: true
    br.validates :bill_to_address_country, presence: true
    br.validates :bill_to_phone, presence: true
    
    br.validates :ship_to_forename, presence: true
    br.validates :ship_to_surname, presence: true
    br.validates :ship_to_address_line1, presence: true
    br.validates :ship_to_address_city, presence: true
    br.validates :ship_to_address_postal_code, presence: true
    br.validates :ship_to_address_state, presence: true
    br.validates :ship_to_address_country, presence: true
    br.validates :ship_to_phone, presence: true
  end

  # aasm :column => :decision do # default column: aasm_state
  #   state :pending, :initial => 'pending'
  #   state :accepted
  #   state :declined
  #   state :rejected
  #   state :other
  #
  #   event :accept do
  #     transitions :from => :pending, :to => :accepted
  #   end
  #
  #   event :decline do
  #     transitions :from => :pending, :to => :declined
  #   end
  #
  #   event :reject do
  #     transitions :from => :pending, :to => :rejected, :after => :notify_competition_closed
  #   end
  #
  #   event :other do
  #     transitions :from => :pending, :to => :other, :after => :notify_competition_closed
  #   end
  # end


end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_filter :authenticate
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  
  def index
    @invoices = Invoice.all
  end
  
  def show
  end
  
  def new
    @invoice = Invoice.new
  end
  
  def edit
  end
  
  def create
    @invoice = Invoice.new(invoice_params)
    
    @invoice.auth_token       = SecureRandom.uuid
    @invoice.security_token   = SecureRandom.hex(16)
    @invoice.transaction_uuid = SecureRandom.uuid
    @invoice.transaction_type = 'authorization'
    
    
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoices_path, notice: 'Invoice was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def reset
    @invoice = Invoice.find_by_id(params[:id])
    
    @invoice.auth_token       = SecureRandom.uuid
    @invoice.security_token   = SecureRandom.hex(16)
    @invoice.transaction_uuid = SecureRandom.uuid
    @invoice.transaction_type = 'authorization'
    @invoice.invoice_status   = 'pending'
    @invoice.decision         = 'pending'
    
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoices_path, notice: 'Invoice was successfully reset' }
      else
        format.html { render :new }
      end
    end
  end
  
  
  def copy
    @old_invoice              = Invoice.find_by_id(params[:id])
    @invoice                  = @old_invoice.dup
    
    # @invoice.parent_id        = @old_invoice.id
    @invoice.auth_token       = SecureRandom.uuid
    @invoice.security_token   = SecureRandom.hex(16)
    @invoice.transaction_uuid = SecureRandom.uuid
    @invoice.transaction_type = 'authorization'
    
    @invoice.signed_date_time    = nil
    @invoice.invoice_status      = 'pending'
    @invoice.customer_ip_address = nil
    
    @invoice.req_card_expiry_date      = nil
    @invoice.reason_code               = nil
    @invoice.req_device_fingerprint_id = nil
    @invoice.decision                  = nil
    @invoice.message                   = nil
    @invoice.transaction_id            = nil
    @invoice.payer_authentication_xid  = nil
    
    respond_to do |format|
      if @invoice.save
        format.html { redirect_to invoices_path, notice: 'Invoice was successfully copied.' }
      else
        format.html { render :new }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    # @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # def failure
  #   UserMailer.transaction_email(1, Invoice.last.id).deliver_later
  # end
  
  protected
  
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['HBL_AUTH_USERNAME_' + ENV['HBL_MODE']] && password == ENV['HBL_AUTH_PASSWORD_' + ENV['HBL_MODE']]
    end
  end
  
  private
  def set_invoice
    @invoice = Invoice.find(params[:id])
  end
  
  def invoice_params
    params.require(:invoice).permit(
        :consumer_id, :amount, :currency, :reference_number,
        :bill_to_forename, :bill_to_surname, :bill_to_email, :bill_to_address_line1, :bill_to_address_city, :bill_to_address_postal_code, :bill_to_address_state, :bill_to_address_country, :bill_to_phone,
        :ship_to_forename, :ship_to_surname, :ship_to_address_line1, :ship_to_address_city, :ship_to_address_postal_code, :ship_to_address_state, :ship_to_address_country, :ship_to_phone
    )
  end


end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.haml
= simple_form_for(@invoice, :defaults => { :input_html => { :class => "input-text-width" } }) do |f|
  = f.error_notification
  .form-inputs.row
    .col-md-4
      %fieldset.fieldset-border
        %legend.fieldset-border Invoice
        = f.input :consumer_id
        = f.input :reference_number, label: 'Invoice Number'
        = f.input :amount
        = f.currency_select :currency, {}, {}, html_options = {style: "width:100%;"}
    .col-md-4
      %fieldset.fieldset-border
        %legend.fieldset-border Billing Information
        = f.input :bill_to_email
        = f.input :bill_to_forename
        = f.input :bill_to_surname
        = f.input :bill_to_address_line1
        = f.input :bill_to_address_city
        = f.input :bill_to_address_postal_code
        = f.input :bill_to_address_state
        = f.country_select :bill_to_address_country
        = f.input :bill_to_phone    
    .col-md-4
      %fieldset.fieldset-border
        %legend.fieldset-border Shipping Information
        %br
        = f.check_box :contact_same_as_above, {class: 'contact_same_as'}, true, false
        = f.label :contact_same_as_above, 'Same as billing information?', style: 'display: inline-block;'
        %br
        %br
        %br
        = f.input :ship_to_forename
        = f.input :ship_to_surname
        = f.input :ship_to_address_line1
        = f.input :ship_to_address_city
        = f.input :ship_to_address_postal_code
        = f.input :ship_to_address_state
        = f.country_select :ship_to_address_country
        = f.input :ship_to_phone
  .form-actions
    = link_to 'Back', invoices_path, class: 'btn btn-default'
    = f.button :submit, class: 'btn btn-primary'

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>
<%= render 'form', invoice: @invoice %>

app/views/invoices/failure.html.erb
sdsd

app/views/invoices/index.html.erb
<h1>Invoices</h1>
<%= link_to 'New Invoice', new_invoice_path, class: 'btn btn-primary pull-right' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Date</th>
      <th>Full Name</th>
      <th>Email</th>
      <th>Amount</th>
      <th>Currency</th>
      <th>Invoice Number</th>
      <th>Status</th>
      <th>Checkout Link</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.created_at.to_date.strftime('%d/%m/%Y') %></td>
        <td><%= "#{invoice.bill_to_surname} #{invoice.bill_to_forename}" %></td>
        <td><%= invoice.bill_to_email %></td>
        <td><%= invoice.amount %></td>
        <td><%= invoice.currency %></td>
        <td><%= invoice.reference_number %></td>
        <td><%= "#{invoice.decision}" %></td>
        <td>
          <% if invoice.decision == 'pending' %>
            <%= link_to "Checkout link", invoice_confirm_edit_path({auth_token: invoice.auth_token, security_token: invoice.security_token}) %>
          <% else %>
            <%= "#{invoice.decision}" %>
          <% end %>
        </td>
        <td>
          <%# url = invoice_confirm_edit_url({auth_token: invoice.auth_token, security_token: invoice.security_token}) %>
          <%#= hidden_field_tag 'client_url', url, class: 'hidden', id:"bar" %>
          <%#= link_to 'copy url', 'javascript:void(0)', class: 'btn btn-sm btn-primary', data_clipboard_target: "#bar" %>

          <%= link_to 'Show', invoice, class: 'btn btn-sm btn-primary' %>
          <% if invoice.decision == 'rejected' || invoice.decision == 'declined' || invoice.decision == 'other' %>
            <%= link_to 'Reset', reset_invoice_path(invoice), class: 'btn btn-sm btn-success' %>
          <% end %>
          <%= link_to 'Copy', copy_invoice_path(invoice), class: 'btn btn-sm btn-warning' %>
          <%= link_to 'Edit', edit_invoice_path(invoice), class: 'btn btn-sm btn-success' %>
          <%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm  btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% content_for(:third_party_js) do %>
    <script src="https://cdn.rawgit.com/zenorocha/clipboard.js/v1.5.10/dist/clipboard.min.js"></script>
<% end %>
<script type="text/javascript">
    $(document).ready(function(){
        $('#myModal').on('shown.bs.modal', function () {
            $('#myInput').focus()
        })
    });

</script>

app/views/invoices/new.html.erb
<div>
  <h1>New Invoice</h1>
  <%= render 'form', invoice: @invoice %>
</div>

app/views/invoices/show.html.haml
.col-md-4
  %fieldset.fieldset-border
    %legend.fieldset-border Invoice details
    .col-sm-6 Transaction UUID:
    .col-sm-6= @invoice.transaction_uuid


    .col-sm-6 Invoice number:
    .col-sm-6= @invoice.reference_number

    .col-sm-6 Amount:
    .col-sm-6= @invoice.amount

    .col-sm-6 Currency:
    .col-sm-6= @invoice.currency

    .col-sm-6 Decision:
    .col-sm-6= @invoice.decision || "nil"

    .col-sm-6 Message:
    .col-sm-6= @invoice.message || "nil"

    .col-sm-6 Transaction ID:
    .col-sm-6= @invoice.transaction_id || "nil"

    .col-sm-6 Reason Code:
    .col-sm-6= @invoice.reason_code || "nil"

.col-md-4
  %fieldset.fieldset-border
    %legend.fieldset-border Billing Information
    .col-sm-6 First Name:
    .col-sm-6= @invoice.bill_to_surname

    .col-sm-6 Last Name:
    .col-sm-6= @invoice.bill_to_forename
    
    .col-sm-6 Email:
    .col-sm-6= @invoice.bill_to_email
    
    .col-sm-6 Address Line1:
    .col-sm-6= @invoice.bill_to_address_line1

    .col-sm-6 City:
    .col-sm-6= @invoice.bill_to_address_city

    .col-sm-6 Postal Code:
    .col-sm-6= @invoice.bill_to_address_postal_code

    .col-sm-6 State:
    .col-sm-6= @invoice.bill_to_address_state

    .col-sm-6 Country:
    .col-sm-6= @invoice.bill_to_address_country

    .col-sm-6 Phone:
    .col-sm-6= @invoice.bill_to_phone
    
.col-md-4
  %fieldset.fieldset-border
    %legend.fieldset-border Shipping Information
    .col-sm-6 First Name:
    .col-sm-6= @invoice.ship_to_surname

    .col-sm-6 Last Name:
    .col-sm-6= @invoice.ship_to_forename

    .col-sm-6 Address Line1:
    .col-sm-6= @invoice.ship_to_address_line1

    .col-sm-6 City:
    .col-sm-6= @invoice.ship_to_address_city

    .col-sm-6 Postal Code:
    .col-sm-6= @invoice.ship_to_address_postal_code

    .col-sm-6 State:
    .col-sm-6= @invoice.ship_to_address_state

    .col-sm-6 Country:
    .col-sm-6= @invoice.ship_to_address_country

    .col-sm-6 Phone:
    .col-sm-6= @invoice.ship_to_phone

.col-md-12
  = link_to 'Back', invoices_path, class: 'btn btn-default'
  = link_to 'Edit', edit_invoice_path(@invoice), class: 'btn btn-primary'