config/routes.rb
Rails.application.routes.draw do
  
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  get 'users/index'

  devise_for :users
  get 'invoice_confirm/edit'
  get 'invoice_confirm/verify'
  put 'invoice_confirm/confirm'
  
  # post 'invoice_confirm/transaction_response'

  match 'invoice_confirm/response' => 'invoice_confirm#transaction_response', via: [:post]
  # post 'invoice_confirm/failure'
  
  resources :users, only:[:index]
  resources :invoices do
    member do
      get :copy
      get :reset
    end
    collection do
      get :failure
    end
  end
  # get 'dashboard/index'

  root 'invoices#index'
end

app/controllers/invoice_confirm_controller.rb
class InvoiceConfirmController < ApplicationController
  # layout false
  
  def edit
    @invoice = Invoice.find_by_auth_token_and_security_token(params[:auth_token], params[:security_token])
    if @invoice.present?
    else
      render plain: "Invoice not found"
    end
  end
  
  def confirm
    @invoice = Invoice.find_by_auth_token_and_security_token(params[:auth_token], params[:security_token])
    
    if @invoice.present? #&& @invoice.invoice_status == 'pending'
      @invoice.attributes          = invoice_confirm_params
      @invoice.is_confirm_invoice  = true
      @invoice.signed_date_time    = signed_date_time
      @invoice.invoice_status      = 'processing'
      @invoice.customer_ip_address = request.remote_ip
      
      respond_to do |format|
        if params[:invoice][:is_terms_and_conditions_accepted] == "1"
          if @invoice.save
            format.html { redirect_to invoice_confirm_verify_path({ auth_token: params[:auth_token], security_token: params[:security_token] }) }
          else
            format.html { render :edit }
          end
        else
          format.html { render :edit }
        end
      end
    else
      render plain: "Invoice not found"
    end
  end
  
  def verify
    @invoice = Invoice.find_by_auth_token_and_security_token(params[:auth_token], params[:security_token])
    
    @signed_field_names = 'merchant_defined_data1,consumer_id,customer_ip_address,access_key,profile_id,transaction_uuid,signed_field_names,unsigned_field_names,signed_date_time,locale,transaction_type,reference_number,amount,currency,'
    @signed_field_names = @signed_field_names + 'bill_to_forename,bill_to_surname,bill_to_email,bill_to_address_line1,bill_to_address_city,bill_to_address_country,bill_to_phone,'
    @signed_field_names = @signed_field_names + 'ship_to_forename,ship_to_surname,ship_to_address_line1,ship_to_address_city,ship_to_address_postal_code,ship_to_address_state,ship_to_address_country,ship_to_phone'
    
    @unsigned_field_names = ''
    
    params[:consumer_id]      = @invoice.consumer_id
    params[:reference_number] = @invoice.reference_number
    params[:amount]           = @invoice.amount
    params[:currency]         = @invoice.currency
    
    params[:bill_to_forename]            = @invoice.bill_to_forename
    params[:bill_to_surname]             = @invoice.bill_to_surname
    params[:bill_to_email]               = @invoice.bill_to_email
    params[:bill_to_address_line1]       = @invoice.bill_to_address_line1
    params[:bill_to_address_city]        = @invoice.bill_to_address_city
    params[:ship_to_address_postal_code] = @invoice.ship_to_address_postal_code
    params[:ship_to_address_state]       = @invoice.ship_to_address_state
    params[:bill_to_address_country]     = @invoice.bill_to_address_country
    params[:bill_to_phone]               = @invoice.bill_to_phone
    
    params[:ship_to_forename]            = @invoice.ship_to_forename
    params[:ship_to_surname]             = @invoice.ship_to_surname
    params[:ship_to_address_line1]       = @invoice.ship_to_address_line1
    params[:ship_to_address_city]        = @invoice.ship_to_address_city
    params[:ship_to_address_postal_code] = @invoice.ship_to_address_postal_code
    params[:ship_to_address_state]       = @invoice.ship_to_address_state
    params[:ship_to_address_country]     = @invoice.ship_to_address_country
    params[:ship_to_phone]               = @invoice.ship_to_phone
    
    
    params[:customer_ip_address]    = @invoice.customer_ip_address
    params[:merchant_defined_data1] = 'WC'
    
    params[:access_key]           = ENV['HBL_ACCESS_KEY_' + ENV['HBL_MODE']]
    params[:profile_id]           = ENV['HBL_PROFILE_KEY_' + ENV['HBL_MODE']]
    params[:transaction_uuid]     = @invoice.transaction_uuid
    params[:signed_field_names]   = @signed_field_names
    params[:unsigned_field_names] = @unsigned_field_names
    params[:signed_date_time]     = @invoice.signed_date_time
    params[:locale]               = 'en'
    params[:transaction_type]     = @invoice.transaction_type
    
    @signature = Security.generate_signature(params)
  
  end
  
  def transaction_response
    @invoice = Invoice.find_by_transaction_uuid(params[:req_transaction_uuid])
    if @invoice.present?
      @invoice.req_card_expiry_date      = params[:req_card_expiry_date]
      @invoice.reason_code               = params[:reason_code]
      @invoice.req_device_fingerprint_id = params[:req_device_fingerprint_id]
      @invoice.decision                  = params[:decision]
      @invoice.message                   = params[:message]
      @invoice.transaction_id            = params[:transaction_id]
      @invoice.payer_authentication_xid  = params[:payer_authentication_xid]
      @invoice.save!
      
      # Send email to admin and client
      UserMailer.transaction_email(1, @invoice.id).deliver_later
    end
  end
  
  private
  
  def invoice_confirm_params
    params.require(:invoice).permit(
        :bill_to_forename, :bill_to_surname, :bill_to_email, :bill_to_address_line1, :bill_to_address_city, :bill_to_address_postal_code, :bill_to_address_state, :bill_to_address_country, :bill_to_phone,
        :ship_to_forename, :ship_to_surname, :ship_to_address_line1, :ship_to_address_city, :ship_to_address_postal_code, :ship_to_address_state, :ship_to_address_country, :ship_to_phone
    )
  end
  
  def signed_date_time
    current_utc_xml_date_time = Time.now.utc.strftime "%Y-%m-%dT%H:%M:%S%z"
    current_utc_xml_date_time = current_utc_xml_date_time[0, current_utc_xml_date_time.length-5]
    current_utc_xml_date_time << 'Z'
    current_utc_xml_date_time
  end

end

app/helpers/invoice_confirm_helper.rb
module InvoiceConfirmHelper
end

app/views/invoice_confirm/confirm.html.erb
<h1>InvoiceConfirm#confirm</h1>
<p>Find me in app/views/invoice_confirm/confirm.html.erb</p>

app/views/invoice_confirm/edit.html.haml
= simple_form_for(@invoice, url: invoice_confirm_confirm_path, method: :put, :defaults => { :input_html => { :class => "input-text-width" } }) do |f|
  = f.error_notification
  = hidden_field_tag :auth_token, params[:auth_token]
  = hidden_field_tag :security_token, params[:security_token]

  .form-inputs.row
    .col-md-4
      %fieldset.fieldset-border
        %legend.fieldset-border Invoice
        = f.input :consumer_id, disabled: true
        = f.input :reference_number, label: 'Invoice Number', disabled: true
        = f.input :amount, disabled: true
        = f.currency_select :currency, {}, {}, html_options = {style: "width:100%;", disabled: true}
        %br
        %br
        - str = "I, the card owner hereby warrants that The source of funds are good, clean and clear, of non-criminal origin, free from any lines and encumbrances, freely transferable and are payable in cash immediately, same day immediate credit upon receipt by the receiving bank. <br/> I, the card Owner also hereby attest and warrant I have never been convicted under, or been the subject of, any investigation with respect to: The Bank Secrecy Act/Anti-Money Laundering (Latest Version); and The Drug Trafficking Act of Pakistan (latest version); and The Criminal Act of Pakistan (latest version); and The Prevention of Terrorism Act of Pakistan (latest version); and The Criminal Justice (International Cooperation) Act of Pakistan (latest version); and The Criminal Justice Act of Pakistan (latest version): and The Electronic Funds Transfer Act Pakistan (latest version). This authorisation is voluntarily and allow the Merchant to transfer funds from my MaterCard / Visa card, under the management of AppsGenii Technologies (Pvt.) Ltd. I do hereby waive / deny my right to file for any claim or demand for any charge back against the amount authorised to be transferred in this Invoice against.".html_safe
        -#= text_area_tag(:terms_condition,
          content = str.html_safe,
            options = {:size =>"38x5" })
        %div.terms_condition_div
          %p
            == I, the card owner hereby warrants that The source of funds are good, clean and clear, of non-criminal origin, free from any lines and encumbrances, freely transferable and are payable in cash immediately, same day immediate credit upon receipt by the receiving bank.
            %br
            == I, the card Owner also hereby attest and warrant I have never been convicted under, or been the subject of, any investigation with respect to:
          %ol
            %li== The Bank Secrecy Act/Anti-Money Laundering (Latest Version); and

            %li== The Drug Trafficking Act of Pakistan (latest version); and

            %li== The Criminal Act of Pakistan (latest version); and

            %li== The Prevention of Terrorism Act of Pakistan (latest version); and

            %li== The Criminal Justice (International Cooperation) Act of Pakistan (latest version); and

            %li== The Criminal Justice Act of Pakistan (latest version): and

            %li== The Electronic Funds Transfer Act Pakistan (latest version).

          %p
            ==This authorisation is voluntarily and allow the Merchant to transfer funds from my MaterCard / Visa card, under the management of AppsGenii Technologies (Pvt.) Ltd.
            %br
            ==I do hereby waive / deny my right to file for any claim or demand for any charge back against the amount authorised to be transferred in this Invoice against.
        %br
        = f.check_box :is_terms_and_conditions_accepted
        == I accept terms & conditions
    .col-md-4
      %fieldset.fieldset-border
        %legend.fieldset-border Billing Information
        = f.input :bill_to_email
        = f.input :bill_to_forename
        = f.input :bill_to_surname
        = f.input :bill_to_address_line1
        = f.input :bill_to_address_city
        = f.input :bill_to_address_postal_code
        = f.input :bill_to_address_state
        = f.country_select :bill_to_address_country
        = f.input :bill_to_phone
    .col-md-4
      %fieldset.fieldset-border
        %legend.fieldset-border Shipping Information
        %br
        = f.check_box :contact_same_as_above, {class: 'contact_same_as'}, true, false
        = f.label :contact_same_as_above, 'Same as billing information?', style: 'display: inline-block;'
        %br
        %br
        %br
        = f.input :ship_to_forename
        = f.input :ship_to_surname
        = f.input :ship_to_address_line1
        = f.input :ship_to_address_city
        = f.input :ship_to_address_postal_code
        = f.input :ship_to_address_state
        = f.country_select :ship_to_address_country
        = f.input :ship_to_phone
  .form-actions
    = link_to 'Back', invoices_path, class: 'btn btn-default'
    = f.button :submit, class: 'btn btn-primary'

app/views/invoice_confirm/failure.html.erb
Failure

app/views/invoice_confirm/response.html.erb
<% if params[:decision] == 'ACCEPT' %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        Dear Customer, Thank you for your payment, Your transaction has been received successfully and your account will be updated accordingly.
      </h3>
    </fieldset>
<% elsif params[:decision] == 'DECLINE' %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        Dear Customer, Your card transaction has been declined by your card issuing bank, Kindly contact your card issuing bank for details.
      </h3>
    </fieldset>
<% elsif params[:decision] == 'REJECT' %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        Dear Customer, Your card transaction has been received and under review, our representative will contact you shortly for further process
      </h3>
    </fieldset>
<% else %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        <%= "#{params[:message]}" %>
      </h3>
    </fieldset>
<% end %>

app/views/invoice_confirm/success.html.erb
<% if params[:decision] == 'ACCEPT' %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        Dear Customer, Thank you for your payment, Your transaction has been received successfully and your account will be updated accordingly.
      </h3>
    </fieldset>
<% elsif params[:decision] == 'DECLINE' %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        Dear Customer, Your card transaction has been declined by your card issuing bank, Kindly contact your card issuing bank for details.
      </h3>
    </fieldset>
<% elsif params[:decision] == 'REJECT' %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        Dear Customer, Your card transaction has been received and under review, our representative will contact you shortly for further process
      </h3>
    </fieldset>
<% else %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        <%= "#{params[:message]}" %>
      </h3>
    </fieldset>
<% end %>

app/views/invoice_confirm/transaction_response.html.erb
<% if params[:decision] == 'ACCEPT' %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        Dear Customer, Thank you for your payment, Your transaction has been received successfully and your account will be updated accordingly.
      </h3>
    </fieldset>
<% elsif params[:decision] == 'DECLINE' %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        Dear Customer, Your card transaction has been declined by your card issuing bank, Kindly contact your card issuing bank for details.
      </h3>
    </fieldset>
<% elsif params[:decision] == 'REJECT' %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        Dear Customer, Your card transaction has been received and under review, our representative will contact you shortly for further process
      </h3>
    </fieldset>
<% else %>
    <fieldset class="fieldset-border">
      <legend class="fieldset-border">Payment Response</legend>
      <h3>
        <%= "#{params[:message]}" %>
      </h3>
    </fieldset>
<% end %>

app/views/invoice_confirm/verify.html.haml
%form#payment_confirmation{:action => ENV['HBL_SUBMIT_FORM_URL_' + ENV['HBL_MODE']], :method => "post"}
  = hidden_field_tag :access_key, ENV['HBL_ACCESS_KEY_' + ENV['HBL_MODE']]
  = hidden_field_tag :profile_id, ENV['HBL_PROFILE_KEY_' + ENV['HBL_MODE']]
  = hidden_field_tag :transaction_uuid, @invoice.transaction_uuid
  = hidden_field_tag :signed_field_names, @signed_field_names
  = hidden_field_tag :unsigned_field_names, @unsigned_field_names
  = hidden_field_tag :signed_date_time, @invoice.signed_date_time
  = hidden_field_tag :locale, 'en'
  = hidden_field_tag :transaction_type, @invoice.transaction_type
  = hidden_field_tag :merchant_defined_data1, "WC"
  = hidden_field_tag :customer_ip_address, @invoice.customer_ip_address
  = hidden_field_tag :signature, @signature
  .col-md-4
    %fieldset.fieldset-border
      %legend.fieldset-border Invoice details
      .col-sm-6 Consumer ID:
      .col-sm-6= @invoice.consumer_id
      = hidden_field_tag :consumer_id, @invoice.consumer_id
  
      .col-sm-6 Invoice number:
      .col-sm-6= @invoice.reference_number
      = hidden_field_tag :reference_number, @invoice.reference_number
  
      .col-sm-6 Amount:
      .col-sm-6= @invoice.amount
      = hidden_field_tag :amount, @invoice.amount
  
      .col-sm-6 Currency:
      .col-sm-6= @invoice.currency
      = hidden_field_tag :currency, @invoice.currency
  .col-md-4
    %fieldset.fieldset-border
      %legend.fieldset-border Billing Information
      .col-sm-6 First Name:
      .col-sm-6= @invoice.bill_to_forename
      = hidden_field_tag :bill_to_forename, @invoice.bill_to_forename
  
      .col-sm-6 Last Name:
      .col-sm-6= @invoice.bill_to_surname
      = hidden_field_tag :bill_to_surname, @invoice.bill_to_surname
  
      .col-sm-6 Email:
      .col-sm-6= @invoice.bill_to_email
      = hidden_field_tag :bill_to_email, @invoice.bill_to_email
  
      .col-sm-6 Billing Address:
      .col-sm-6= @invoice.bill_to_address_line1
      = hidden_field_tag :bill_to_address_line1, @invoice.bill_to_address_line1
  
      .col-sm-6 Billing City:
      .col-sm-6= @invoice.bill_to_address_city
      = hidden_field_tag :bill_to_address_city, @invoice.bill_to_address_city
  
      .col-sm-6 Billing Postal Code:
      .col-sm-6= @invoice.bill_to_address_postal_code
      = hidden_field_tag :bill_to_address_postal_code, @invoice.bill_to_address_postal_code
  
      .col-sm-6 Billing State:
      .col-sm-6= @invoice.bill_to_address_state
      = hidden_field_tag :bill_to_address_state, @invoice.bill_to_address_state
  
      .col-sm-6 Billing Country:
      .col-sm-6= @invoice.bill_to_address_country
      = hidden_field_tag :bill_to_address_country, @invoice.bill_to_address_country
  
      .col-sm-6 Phone:
      .col-sm-6= @invoice.bill_to_phone
      = hidden_field_tag :bill_to_phone, @invoice.bill_to_phone
  .col-md-4
    %fieldset.fieldset-border
      %legend.fieldset-border Shipping Information
      .col-sm-6 First Name:
      .col-sm-6= @invoice.ship_to_forename
      = hidden_field_tag :ship_to_forename, @invoice.ship_to_forename

      .col-sm-6 Last Name:
      .col-sm-6= @invoice.ship_to_surname
      = hidden_field_tag :ship_to_surname, @invoice.ship_to_surname

      .col-sm-6 Shipping Address:
      .col-sm-6= @invoice.ship_to_address_line1
      = hidden_field_tag :ship_to_address_line1, @invoice.ship_to_address_line1

      .col-sm-6 Shipping City:
      .col-sm-6= @invoice.ship_to_address_city
      = hidden_field_tag :ship_to_address_city, @invoice.ship_to_address_city

      .col-sm-6 Shipping Postal Code:
      .col-sm-6= @invoice.ship_to_address_postal_code
      = hidden_field_tag :ship_to_address_postal_code, @invoice.ship_to_address_postal_code

      .col-sm-6 Shipping State:
      .col-sm-6= @invoice.ship_to_address_state
      = hidden_field_tag :ship_to_address_state, @invoice.ship_to_address_state

      .col-sm-6 Shipping Country:
      .col-sm-6= @invoice.ship_to_address_country
      = hidden_field_tag :ship_to_address_country, @invoice.ship_to_address_country

      .col-sm-6 Phone:
      .col-sm-6= @invoice.ship_to_phone
      = hidden_field_tag :ship_to_phone, @invoice.ship_to_phone
  .row
    .col-md-12
      %p
        == I, the card owner hereby warrants that The source of funds are good, clean and clear, of non-criminal origin, free from any lines and encumbrances, freely transferable and are payable in cash immediately, same day immediate credit upon receipt by the receiving bank.
        %br
        == I, the card Owner also hereby attest and warrant I have never been convicted under, or been the subject of, any investigation with respect to:
      %ol
        %li== The Bank Secrecy Act/Anti-Money Laundering (Latest Version); and

        %li== The Drug Trafficking Act of Pakistan (latest version); and

        %li== The Criminal Act of Pakistan (latest version); and

        %li== The Prevention of Terrorism Act of Pakistan (latest version); and

        %li== The Criminal Justice (International Cooperation) Act of Pakistan (latest version); and

        %li== The Criminal Justice Act of Pakistan (latest version): and

        %li== The Electronic Funds Transfer Act Pakistan (latest version).

      %p
        ==This authorisation is voluntarily and allow the Merchant to transfer funds from my MaterCard / Visa card, under the management of AppsGenii Technologies (Pvt.) Ltd.
        %br
        ==I do hereby waive / deny my right to file for any claim or demand for any charge back against the amount authorised to be transferred in this Invoice against.

  = link_to 'Edit', invoice_confirm_edit_path({auth_token: @invoice.auth_token, security_token: @invoice.security_token}), class: 'btn btn-default'
  %input#submit.btn.btn-primary{:type => "submit", :value => "Confirm"}/
%br
%br
%br