config/routes.rb
Rails.application.routes.draw do
  
  
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  
  get 'users/index'

  devise_for :users
  get 'invoice_confirm/edit'
  get 'invoice_confirm/verify'
  put 'invoice_confirm/confirm'
  
  # post 'invoice_confirm/transaction_response'

  match 'invoice_confirm/response' => 'invoice_confirm#transaction_response', via: [:post]
  # post 'invoice_confirm/failure'
  
  resources :users, only:[:index]
  resources :invoices do
    member do
      get :copy
      get :reset
    end
    collection do
      get :failure
    end
  end
  # get 'dashboard/index'

  root 'invoices#index'
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.haml
-#.centered
-#  = image_tag 'AppsGenii-Technologies.png'
%nav.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle{data_toggle: "collapse", data_target: "#myNavbar", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: "#"} AppsGenii
    #myNavbar.collapse.navbar-collapse
      %ul.nav.navbar-nav
        %li
          = link_to 'Users', users_path
        %li
          = link_to 'Invoices', invoices_path
      %ul.nav.navbar-nav.navbar-right
        - if current_user.present?
          %li
            = link_to 'Edit account', edit_user_registration_path
          %li
            = link_to 'Sign out', destroy_user_session_path, :method=>'delete'
        - else
          -#%li
          -#  %a{href: "#"}
          -#    %span.glyphicon.glyphicon-user
          -#    Sign Up
          %li
            %a{href: "#"}
              %span.glyphicon.glyphicon-user
              Sign In

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= "HBLPaymentGateway" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "HBLPaymentGateway" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= yield :third_party_js %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div>
      <%= render 'layouts/navigation' %>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ENT Book Submission" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "ENT Book Submission" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>
  <body>
    <div class="navbar navbar-fixed-top navbar-inverse" >
      <a class='btn btn-navbar' data-target='.nav-collapse' data-toggle='collapse'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
      </a>

      <a class='brand' href='/'>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
        <span class='icon-bar'></span>
         <img src='/assets/favicon.ico'>
      </a>
        
      <nav class="navbar-inner" style="background-color: black">
        <div class="container" >
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%#= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>